#!/bin/bash
# This function sets up any .ttf fonts contained in the <fonts> directory to be detected by matplotlib
# Normally matplotlib just includes a couple open-source .ttf files, but this way we can carry many more
# options across different systems.
# See: https://olgabotvinnik.com/blog/2012-11-15-how-to-set-helvetica-as-the-default-sans-serif-font-in/
# To add a font on Mac: might be as .ttf or as .dfont, but find it in either
# /System/Library/Font *OR* /Library/Fonts, then use "fondu" library (can be BREW INSTALLED)
# Install new fonts with: "brew cask install font-source-code-pro" after using
# "brew tap caskroom/fonts" to initialize; these will appear in ~/Library/Fonts

# First add the fonts
base=pubplot/fonts
mpldir=$(python -c "import matplotlib; print(matplotlib.matplotlib_fname())")
mfontdir=${mpldir%matplotlibrc}/fonts/ttf
echo "Transfering .ttf files in \"fonts\" folder to $mfontdir..."
for font in $base/*.ttf; do
  if [ ! -r "$mfontdir/${font##*/}" ]; then
    echo "Adding font \"${font##*/}\"..."
    cp "$font" "$mfontdir/"
  fi
done

# Then delete the cache; echo each one
# For get_cachedir see: https://stackoverflow.com/a/24196416/4970632
shopt -s nullglob # keep empty if does not exist
cachedir=$(python -c "import matplotlib; print(matplotlib.get_cachedir())")
caches=($cachedir/*.cache) # may be more than one
for cache in ${caches[@]}; do # might be more than one
  if [ ! -d "$cache" ]; then # may be a tex.cache folder
    echo "Deleting cache \"$cache\"..."
    rm "$cache"
  fi
done
