#!/bin/bash
# This function sets up any .ttf fonts contained in the <fonts> directory to be detected by matplotlib
# Normally matplotlib just includes a couple open-source .ttf files, but this way we can carry many more
# options across different systems.
# See: http://www.claridgechang.net/blog/how-to-use-custom-fonts-in-matplotlib
# Also: https://olgabotvinnik.com/blog/2012-11-15-how-to-set-helvetica-as-the-default-sans-serif-font-in/

# First add the fonts
mpldir=$(python -c "import matplotlib; print(matplotlib.matplotlib_fname())")
mfontdir=${mpldir%matplotlibrc}/fonts/ttf
echo "Transfering .ttf files in \"fonts\" folder to $mfontdir..."
for font in fonts/*.ttf; do
  echo $mfontdir/${font##*/}
  if [ ! -r $mfontdir/${font##*/} ]; then
    echo "Adding font \"${font##*/}\"..."
    cp $font $mfontdir/
  fi
done

# Then delete the cache; echo each one
caches=(~/.matplotlib/*.cache)
for cache in ${caches[@]}; do # might be more than one
  if [ ! -d $cache ]; then # may be a tex.cache folder
    echo "Deleting cache \"$cache\"..."
    rm $cache
  fi
done
